openapi: 3.0.3
info:
  title: Jupyter Cassini API Spec
  version: 0.3.0
servers:
  - url: http://localhost:8888/jupyter_cassini/
security:
  - auth: []
components:
  securitySchemes:
    auth:
      type: apiKey
      name: token
      in: query
  schemas:
    Status:
      type: object
      properties:
        status: 
          type: string
          enum:
            - success
            - failure
      required:
        - status

    TierInfo:
      type: object
      oneOf:
        - $ref: "#/components/schemas/FolderTierInfo"
        - $ref: "#/components/schemas/NotebookTierInfo"
      discriminator:
        propertyName: tierType
        mapping:
          folder: "#/components/schemas/FolderTierInfo"
          notebook: "#/components/schemas/NotebookTierInfo"
    
    CommontTierInfo:
      type: object
      properties:
        name:
          type: string
        identifiers:
          type: array
          items: 
            type: string
        children:
          type: array
          items:
            type: string
      required:
        - name
        - identifiers
    
    FolderTierInfo:
      type: object
      allOf:
        - $ref: "#/components/schemas/CommontTierInfo"
      
    NotebookTierInfo:
      type: object
      allOf:
        - $ref: "#/components/schemas/CommontTierInfo"
      properties:
        started: 
          type: string
          format: date-time
      required:
        - started

    metaSchema:
      type: object
      properties:
        properties:
          type: object
          additionalProperties:
            type: object
            properties:
              title:
                type: string
              type:
                type: string
              default: {}
              format: 
                type: string
          required:
            - title
            - type
      required:
        - properties

    ChildClsInfo:
      type: object
      oneOf:
        - $ref: "#/components/schemas/ChildClsFolderInfo"
        - $ref: "#/components/schemas/ChildClsNotebookInfo"     
      discriminator:
        propertyName: tierType
        mapping:
          folder: "#/components/schemas/ChildClsFolderInfo"
          notebook: "#/components/schemas/ChildClsNotebookInfo"
    
    CommonChildClsInfo:
      type: object
      properties:
        name:
          type: string
        idRegex:
          type: string
        namePartTemplate:
          type: string

    ChildClsFolderInfo:
      type: object
      allOf:
        - $ref: "#/components/schemas/CommonChildClsInfo"
      
    ChildClsNotebookInfo:
      type: object
      allOf:
        - $ref: "#/components/schemas/CommonChildClsInfo"
      properties:
        templates:
          type: array
          items: 
            type: string
        metaNames:
          type: array
          items: 
            type: string
        metaSchema:
            $ref: "#/components/schemas/metaSchema"
      required:
        - templates
        - metaNames
        - metaSchema

    TreeChildResponse:
      type: object
      properties:
        name:
          type: string
        info:
          type: string
        outcome:
          type: string
        started:
          type: string
          format: date-time
        hltsPath:
          type: string
        metaPath:
          type: string
        notebookPath:
          type: string
        additionalMeta:
          type: object
          additionalProperties: true
      required:
        - name
    TreeResponse:
      type: object
      allOf:
        - $ref: "#/components/schemas/TreeChildResponse"
      properties:
        folder:
          type: string
        childClsInfo:          
          $ref: "#/components/schemas/ChildClsInfo"
        children:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/TreeChildResponse"
      required:
        - name
        - folder
        - children

    NewChildInfo:
      type: object
      properties:
        id:
          type: string
        parent:
          type: string
        template:
          type: string
      additionalProperties: true
      required:
        - id
        - parent

paths: 
  /lookup:
      get:
        summary: Lookup a tier
        description: Look up a tier by name and respond with info about it.
        parameters:
        - name: name
          in: query
          schema:
            type: string
          required: true

        responses:
          "200":
            description: "Tier Found"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/TierInfo"
          "404":
            description: "Not Found"
  /tree:
    get:
      summary: View the tier tree
      description: Get the children of a particular tier (or home)
      parameters:
      - name: ids[]
        in: query
        schema:
          type: array
          items:
            type: string
        style: form
        explode: false
      responses:
        "200":
          description: Found tree
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TreeResponse"
        "404":
          description: "Not Found"
  /open:
    get:
      summary: Open a tier in file explorer
      description: Use `tier.open_folder()` python side on specified tier.
      parameters:
        - name: name
          in: query
          schema:
            type: string
          required: true
      responses:
        "200":
          description: Open successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Status"
        "404":
          description: Not Found
  /newChild:
    post:
      summary: Create a new child
      description: Create a new child
      requestBody:
        content:
          application/json:
            schema: 
              $ref: "#/components/schemas/NewChildInfo"
      responses:
        "200":
          description: Child made
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TreeResponse"


